import type { Concept, StageId, SubjectId } from "./types";

// Compact authoring format: [id, stage, title, blurb, lesson, prereqs, misconceptionIds?]
type Row = [string, StageId, string, string, string, string[], string[]?];

function build(subject: SubjectId, rows: Row[]): Concept[] {
  return rows.map(([id, stage, title, blurb, lesson, prereqs, misconceptions]) => ({
    id, subject, stage, title, blurb, lesson, prereqs, misconceptions: misconceptions ?? [],
  }));
}

// ─────────────────────────────────────────────────────────────────────────────
// MATHEMATICS — 72 concepts, stage 0 (primary foundations) → stage 5 (frontier)
// ─────────────────────────────────────────────────────────────────────────────
const MATHS: Row[] = [
  ["place-value", 0, "Place value", "Digits mean different amounts depending on their position.", "In the number 452, the digit 4 means 400, the 5 means 50 and the 2 means 2. Each step left multiplies a digit's value by ten, and each step right divides it by ten. This single idea is why we can write enormous numbers compactly, and it is the foundation of decimal numbers, estimation and standard form later on.", []],
  ["addition", 0, "Addition", "Combining quantities into a total.", "Adding means putting quantities together: 3 sweets + 4 sweets = 7 sweets. The column method lines up place values so ones add to ones, tens to tens, carrying groups of ten leftwards when a column overflows. Fluency here is not about speed for its own sake — it frees your working memory for harder ideas built on top.", []],
  ["subtraction", 0, "Subtraction", "Taking one quantity away, or finding the difference.", "Subtraction answers two questions: how much is left after taking away, and how far apart two numbers are. The column method borrows from the next place value when a digit cannot be reduced. A key early insight: subtraction is the inverse of addition, so you can always check an answer by adding back.", []],
  ["multiplication", 0, "Multiplication", "Repeated addition of equal groups.", "4 × 3 means four groups of three: 3 + 3 + 3 + 3 = 12. Times tables are the alphabet of arithmetic — knowing them by heart lets you factorise, estimate and spot patterns instantly. The grid and column methods break big products into place-value chunks: 23 × 4 = (20 × 4) + (3 × 4).", []],
  ["division", 0, "Division", "Sharing into equal groups, the inverse of multiplication.", "12 ÷ 3 asks either 'how many groups of 3 fit in 12?' (4) or 'if 12 is shared into 3 equal parts, how big is each part?' (4). Long division splits the number by place value. Remainders matter: 13 ÷ 4 = 3 remainder 1, which later becomes the fraction 3¼ and the decimal 3.25.", []],
  ["negatives", 0, "Negative numbers", "Numbers below zero, and how operations behave with them.", "A negative is an amount below zero — temperatures, debt, depths. The rules that matter: subtracting a negative adds (5 − (−3) = 8), multiplying two negatives makes a positive ((−2) × (−3) = 6), and one negative makes a negative. Picture a number line: adding moves right, subtracting moves left.", [], ["neg-slip"]],
  ["fractions", 0, "Fractions", "Equal parts of a whole, written as a ratio of two integers.", "A fraction a/b means a parts, each of size 1/b. The bottom number names the size of the part; the top counts them. 1/4 of a pizza is bigger than 1/8 because quarters are bigger slices. Equivalent fractions (1/2 = 3/6) multiply top and bottom by the same number — the value doesn't change because you're scaling both part-size and count equally.", [], ["frac-slice"]],
  ["fraction-ops", 1, "Fraction arithmetic", "Adding, subtracting, multiplying and dividing fractions.", "Add or subtract with a common denominator: 1/3 + 1/4 = 4/12 + 3/12 = 7/12. Multiply straight across: 2/3 × 3/5 = 6/15 = 2/5. Divide by flipping the second fraction and multiplying: 2/3 ÷ 1/6 = 2/3 × 6/1 = 4. The flip works because dividing by 1/6 asks 'how many sixths fit?' — and there are 6 sixths in every whole.", ["fractions"], ["denom-add"]],
  ["decimals", 0, "Decimals", "Fractions with denominators of ten, written in place value.", "0.3 is 3/10; 0.07 is 7/100. Decimal place value extends the same left-right logic as whole numbers. Comparing decimals: line up place value — 0.09 < 0.1 even though 9 > 1. Multiplying shifts the point: 0.3 × 0.2 = 0.06 because tenths times tenths are hundredths.", []],
  ["percentages", 1, "Percentages", "Fractions out of 100, used for comparisons, change and interest.", "Percent means 'per hundred': 45% = 45/100 = 0.45. Percentage of an amount: 15% of 60 = 0.15 × 60 = 9. Percentage change = (new − old)/old × 100. A classic trap: a 20% rise then a 20% fall does not return to the start — 100 → 120 → 96 — because the second percentage acts on a different base.", ["fractions", "decimals"], ["pct-base"]],
  ["ratio", 1, "Ratio", "Comparing parts to each other rather than to a whole.", "A ratio 3 : 2 says one part is 3 units for every 2 of the other — it compares part to part, while a fraction compares part to whole. Sharing 250 g in ratio 3 : 2: there are 5 parts, each 50 g, so 150 g and 100 g. Scaling a recipe for 4 people to 6 people multiplies every quantity by 6/4 — every part scales together.", []],
  ["proportion", 1, "Proportion", "Relationships where two quantities scale together.", "Direct proportion: y = kx — double one, double the other (cost of 5 kg at a fixed price per kg). Inverse proportion: y = k/x — double one, halve the other (workers vs time for a fixed job). The constant of proportionality k is the engine of the relationship; finding it is always step one.", ["ratio"], ["inv-prop"]],
  ["rounding", 0, "Rounding & estimation", "Simplifying numbers to a sensible accuracy.", "To round to the nearest ten, look at the ones digit: 5 or more rounds up. 47 → 50; 43 → 40. Estimation uses rounded values to sense-check exact work: 198 × 41 ≈ 200 × 40 = 8000, so an answer of 81,180 is instantly suspicious. Choose significant figures when the size matters more than the digits.", [], ["round-half"]],
  ["order-ops", 0, "Order of operations", "The universal convention for evaluating expressions.", "Brackets, then Indices/Exponents, then Division and Multiplication left to right, then Addition and Subtraction left to right (BIDMAS/PEMDAS). 3 + 4 × 2 = 3 + 8 = 11, not 14 — multiplication always acts first. The convention exists so everyone in the world reads one expression the same way.", [], ["order-ops"]],
  ["indices-intro", 1, "Index laws", "Powers, and the rules for multiplying and dividing them.", "a³ means a × a × a. Multiplying powers with the same base adds the indices: a² × a³ = a⁵. Dividing subtracts them: a⁵ ÷ a² = a³. A power of zero gives 1 (a⁰ = 1) because dividing aⁿ by aⁿ must give 1. Negative indices flip into a fraction: a⁻² = 1/a². Fractional indices are roots: a^(1/2) = √a.", ["order-ops"], ["neg-exp"]],
  ["standard-form", 2, "Standard form", "Writing very large or small numbers as A × 10ⁿ.", "Standard form is A × 10ⁿ where 1 ≤ A < 10. The Sun's mass 2 000 000 000 000 000 000 000 000 000 000 kg becomes 2 × 10³⁰ kg; a red blood cell's 0.000008 m becomes 8 × 10⁻⁶ m. Multiplying multiplies the A's and adds the n's. It is the working language of physics, chemistry and astronomy.", ["indices-intro", "place-value"], ["sf-sig"]],
  ["algebra-expressions", 1, "Algebraic expressions", "Using letters for unknown and variable numbers.", "A letter holds a place for a number: 3x + 2 means 'three of something, plus two'. Collecting like terms simplifies: 3x + 2x = 5x, but 3x + 2y stays put. Expanding brackets multiplies every term inside: 3(x + 4) = 3x + 12. Substitution replaces letters with values: if x = −2, then 3x + 2 = −4.", ["order-ops"], ["like-terms"]],
  ["algebra-expand", 2, "Expanding & factorising", "Multiplying out brackets, and reversing the process.", "Expand: (x + 3)(x + 2) = x² + 5x + 6 — every term meets every term. Factorising reverses it: x² + 5x + 6 seeks two numbers that multiply to 6 and add to 5: (x + 2)(x + 3). The difference of two squares is a shortcut: x² − 9 = (x + 3)(x − 3). These skills are the grammar of every later algebra topic.", ["algebra-expressions"], ["sign-slip"]],
  ["linear-equations", 1, "Linear equations", "Solving for an unknown with inverse operations.", "Solve 3x + 5 = 20 by undoing operations in reverse order: subtract 5 (3x = 15), divide by 3 (x = 5). Whatever you do to one side, do to the other — the equation is a balance. Two-step, brackets, unknowns on both sides (5x = 2x + 9) all reduce to the same discipline.", ["algebra-expressions"], ["bal-slip"]],
  ["inequalities", 2, "Inequalities", "Comparisons and regions: <, ≤, >, ≥.", "x > 3 is every number bigger than 3, drawn as an open circle with an arrow. Solving works like equations, with one famous exception: multiplying or dividing by a negative flips the sign (−2x < 6 becomes x > −3). Compound forms like 3 ≤ x < 8 describe a range; inequalities in two variables describe regions of the plane.", ["linear-equations"], ["ineq-flip"]],
  ["simultaneous", 2, "Simultaneous equations", "Finding values that satisfy two equations at once.", "Two unknowns need two independent equations. Elimination lines terms up and subtracts: 3x + 2y = 16 and 3x + y = 10, subtract to get y = 6, then back-substitute. Substitution solves one equation for a letter and inserts it into the other. Graphically, the solution is the single point where the two lines cross.", ["linear-equations"], ["sub-sign"]],
  ["coordinates", 1, "Coordinates & graphs", "Points on a grid, and curves as pictures of equations.", "A coordinate pair (3, −2) pinpoints a location: 3 right, 2 down from the origin. The x-axis runs horizontally, y vertically. Plotting an equation's points and joining them reveals its shape — lines for linear, parabolas for quadratics. Graphs turn algebra into geometry you can see.", ["negatives"]],
  ["straight-lines", 2, "Straight line graphs", "Gradient and intercept: y = mx + c.", "In y = mx + c, m is the gradient (rise over run — how much y grows per unit of x) and c is where the line crosses the y-axis. Parallel lines share m; perpendicular lines multiply to −1. From two points, m = (y₂ − y₁)/(x₂ − x₁). Every real-world rate — speed, cost per item, fuel use — is a gradient.", ["coordinates", "linear-equations"], ["grad-run"]],
  ["quadratics", 3, "Quadratic equations", "Solving equations of the form ax² + bx + c = 0.", "Quadratics can have two, one, or no real solutions — visible as where the parabola cuts the x-axis. Solve by factorising (x² − 5x + 6 = 0 → (x−2)(x−3) = 0 → x = 2 or 3), by completing the square, or by the quadratic formula x = (−b ± √(b² − 4ac)) / 2a. The discriminant b² − 4ac tells you how many solutions exist before you solve.", ["algebra-expand", "straight-lines"], ["lost-root"]],
  ["sim-equations-quad", 3, "Simultaneous with quadratics", "Line–curve intersections solved algebraically.", "Substitute the linear equation into the quadratic: y = x + 3 into y = x² + 1 gives x + 3 = x² + 1, a quadratic in x alone. Solve it, then back-substitute for y. Each real pair (x, y) is an intersection point of the line and the curve — up to two for a line and a quadratic.", ["quadratics", "simultaneous"], ["lost-root"]],
  ["sequences", 1, "Sequences", "Ordered patterns and their rules.", "A sequence follows a rule: 4, 7, 10, 13 grows by 3 each time — an arithmetic sequence with term-to-term rule +3. Its nth term is 3n + 1 (the common difference times n, adjusted to hit the first term). Quadratic sequences have a constant second difference; geometric ones multiply by a fixed ratio.", [], ["nth-term"]],
  ["functions", 3, "Functions & notation", "Machines mapping inputs to outputs: f(x).", "A function is a rule assigning each input exactly one output. f(x) = 2x + 3 means: take x, double it, add three. f(4) = 11. Composition chains machines: g(f(x)) applies f first, then g. Inverse functions run the machine backwards, swapping x and y. Domain is what goes in; range is what can come out.", ["algebra-expressions", "coordinates"]],
  ["trig-ratios", 2, "Trigonometry", "Sides and angles of right triangles via sin, cos, tan.", "In a right triangle, SOH-CAH-TOA: sin θ = opposite/hypotenuse, cos θ = adjacent/hypotenuse, tan θ = opposite/adjacent. Know one angle and one side, and trig finds the rest. Angles of elevation, navigation, heights of buildings — the same three ratios solve them all. Your calculator's angle mode (degrees vs radians) matters from day one.", ["straight-lines", "proportion"], ["deg-rad", "hyp-leg-trig"]],
  ["trig-identity", 4, "Trig identities & graphs", "Exact values, wave graphs, and the core identities.", "sin²θ + cos²θ = 1 for every angle — it is Pythagoras living on the unit circle. tan θ = sin θ / cos θ. The sine and cosine graphs are waves of period 360°, amplitude 1; tan repeats every 180°. Exact values (sin 30° = 1/2, cos 60° = 1/2, tan 45° = 1) come from the half-square and half-equilateral triangles.", ["trig-ratios", "functions"]],
  ["circle-theorems", 3, "Circle theorems", "Angle facts that are always true inside circles.", "The angle at the centre is twice the angle at the circumference from the same arc. Angles in the same segment are equal. The angle in a semicircle is 90°. Opposite angles of a cyclic quadrilateral sum to 180°. A tangent meets a radius at 90°. These facts crack geometry problems that look impossible at first glance.", ["angles-lines"], ["same-seg"]],
  ["pythagoras", 2, "Pythagoras' theorem", "a² + b² = c² in every right triangle.", "In any right triangle, the square on the hypotenuse equals the sum of squares on the other sides: a² + b² = c². It finds distances everywhere — ladder against a wall, diagonal of a screen, distance between grid points. Its converse also holds: if a² + b² = c², the triangle must be right-angled. The 3-4-5 triangle is the oldest shortcut in construction.", ["indices-intro"], ["hyp-leg"]],
  ["angles-lines", 1, "Angles & polygons", "Angle facts on lines, around points and in polygons.", "Angles on a straight line sum to 180°, around a point to 360°, and vertically opposite angles are equal. In triangles: interior angles sum to 180°. A polygon with n sides has interior sum (n − 2) × 180°, so regular hexagon angles are 120°. Parallel lines create equal corresponding and alternate angles.", [], ["alt-corr"]],
  ["area-perimeter", 1, "Area & perimeter", "Measuring regions and their boundaries.", "Perimeter is the walk around the edge; area is the paint inside. Rectangles: A = lw. Triangles: A = ½bh. Parallelograms and trapezia have derived formulas. Compound shapes split into rectangles and triangles. Beware units: area is squared units, so 1 m = 100 cm but 1 m² = 10 000 cm².", [], ["unit-sq"]],
  ["volume", 2, "Volume & surface area", "Filling 3-D solids and wrapping them.", "Volume counts unit cubes: cuboid V = lwh; prism V = (cross-section area) × length; cylinder V = πr²h. Surface area wraps every face — nets make it visible. Cones (V = ⅓πr²h) and spheres (V = 4/3 πr³) follow. Scale factor k on lengths scales area by k² and volume by k³ — the reason big animals can't look like small ones.", ["area-perimeter"], ["unit-sq"]],
  ["transformations", 2, "Transformations", "Translation, rotation, reflection, enlargement.", "Four moves: translation slides, rotation spins about a centre, reflection flips in a mirror line, enlargement scales from a centre by a scale factor. Describe each fully — direction, angle/centre, line, factor — or perform them on grid. Negative and fractional scale factors take it further: k = ½ shrinks, k = −1 rotates 180° and flips.", ["coordinates"], ["sf-area"]],
  ["vectors", 3, "Vectors", "Quantities with size and direction.", "A vector carries both magnitude and direction, written (3, −2) or as a journey '3 right, 2 down'. Equal vectors match components; scalar multiples stretch them; adding chains journeys tip-to-tail. Vector arithmetic proves geometric facts (parallel midpoints, collinearity) without measuring a single angle.", ["coordinates"], ["vec-dir"]],
  ["probability-basics", 1, "Probability", "Measuring likelihood from 0 to 1.", "Probability = favourable outcomes ÷ total outcomes, always between 0 (impossible) and 1 (certain). Flipping a fair coin: P(heads) = 0.5. All outcomes sum to 1, so P(not A) = 1 − P(A). Experimental probability converges on theory as trials grow — the law of large numbers in miniature.", [], ["sum-one"]],
  ["tree-diagrams", 2, "Tree diagrams & combined events", "Multiplying along branches, adding across outcomes.", "For independent events, multiply along a path: two heads in a row = ½ × ½ = ¼. Tree diagrams lay every path out; probabilities of complete outcome sets sum to 1. 'At least one' is easiest via the complement: P(at least one head in 3 flips) = 1 − (½)³ = 7/8. Without replacement, denominators shrink — the branches are not equal.", ["probability-basics"], ["ind-dep"]],
  ["averages", 1, "Averages & spread", "Mean, median, mode, range — and when to use each.", "The mean adds everything and divides — sensitive to outliers. The median is the middle value when sorted — robust to extremes. The mode is the most frequent — the only average for categories. Range measures spread crudely. The honest question is always: which average answers this question without misleading?", [], ["outlier-mean"]],
  ["data-charts", 1, "Data representation", "Charts, tables, and honest visual summaries.", "Bar charts compare categories, line graphs show trends over time, pie charts show shares of a whole, scatter graphs reveal correlation between two variables. Every chart embeds choices — scales, truncation, grouping — that can inform or mislead. Reading a chart critically is a life skill as much as a maths one.", ["averages"]],
  ["scatter-correlation", 2, "Correlation & regression basics", "Measuring and modelling relationships between variables.", "Scatter graphs show correlation: positive (both rise), negative (one rises, one falls), or none. Correlation is not causation — ice-cream sales and drownings rise together because of summer. A line of best fit lets you interpolate safely and extrapolate with caution. Outliers can drag the whole line.", ["data-charts", "straight-lines"], ["corr-cause"]],
  ["surds", 3, "Surds", "Exact irrational roots left in root form.", "√2 cannot be written exactly as a fraction — its decimal never repeats. A surd is an exact root like √2, √3, √5. Simplify using √(ab) = √a × √b: √50 = √25 × √2 = 5√2. Rationalise denominators by multiplying top and bottom by the surd (or its conjugate for expressions like 1/(1+√2)). Surds keep answers exact where decimals only approximate.", ["indices-intro"], ["sqrt-prod"]],
  ["completing-square", 3, "Completing the square", "Rewriting quadratics to reveal their turning point.", "x² + 6x + 5 = (x + 3)² − 4: halve the x coefficient, square it, adjust. This form exposes the vertex (−3, −4) instantly, shows the minimum/maximum value, and solves equations by isolating a perfect square. It is also how the quadratic formula is derived — completing the square on the general equation.", ["quadratics"], ["b-half"]],
  ["polynomials", 4, "Polynomials & factor theorem", "Higher-degree expressions and their roots.", "Cubics and beyond: degree n gives at most n real roots and a distinctive end-behaviour. The factor theorem: if substituting x = a gives 0, then (x − a) is a factor. Algebraic division or synthetic division strips factors one by one. Knowing one root (say x = 2) often unlocks the rest by factorising what remains.", ["algebra-expand", "quadratics"]],
  ["binomial", 4, "Binomial expansion", "Expanding (a + b)ⁿ with Pascal's triangle.", "Pascal's triangle encodes the coefficients of (a + b)ⁿ: row n gives 1, n, n(n−1)/2, … Each term takes powers that sum to n: (x + 2)³ = x³ + 6x² + 12x + 8. Combinations C(n, r) pick terms for any expansion without building the whole triangle. Approximations like (1 + x)ⁿ ≈ 1 + nx power estimation across science and finance.", ["polynomials", "indices-intro"], ["row-n"]],
  ["trig-rule", 3, "Sine & cosine rules", "Triangles without right angles.", "The sine rule a/sin A = b/sin B solves triangles given any angle-plus-opposite pair. The cosine rule c² = a² + b² − 2ab cos C generalises Pythagoras to non-right triangles — use it with two sides and the enclosed angle, or to find an angle from three sides. Areas come from A = ½ab sin C.", ["trig-ratios", "pythagoras"], ["cos-amb"]],
  ["circle-area-arc", 2, "Arcs, sectors & circles", "Fractions of circles: arcs, sectors, tangents.", "A sector is a pizza slice: area = (θ/360) × πr², arc length = (θ/360) × 2πr — always fraction-of-circle times the full measure. Tangent from an external point, chord properties and π itself all live here. Radian measure (θ/2π as the fraction) becomes the natural unit at A-level.", ["area-perimeter"]],
  ["mixture-problems", 2, "Word problems & modelling", "Turning sentences into equations.", "The core skill: read, define variables, translate, solve, check against the story. 'Three more than twice a number is 17' → 2x + 3 = 17. Ratios of mixtures, journey times, work rates ('two painters together'), and money problems all become linear or simultaneous systems. Always sanity-check the solution in the original words — algebra finds the maths' answer, modelling finds the situation's.", ["linear-equations", "ratio"], ["bal-slip"]],
  ["growth-decay", 3, "Exponential growth & decay", "Repeated proportional change: y = a·kˣ.", "Processes where change is proportional to current size grow exponentially: compound interest A = P(1 + r)ⁿ, population growth, radioactive decay A = A₀·(1/2)^(t/h). Doubling time and half-life are the fingerprints. Exponential beats any polynomial eventually — the reason compound interest and epidemics surprise people.", ["indices-intro", "percentages"], ["simple-cp"]],
  ["logs", 5, "Logarithms", "The inverse of exponentials: log_a(b) asks 'what power?'.", "log₂ 8 = 3 because 2³ = 8. Logs invert exponentials: if y = aˣ then x = log_a y. Laws mirror indices: log(xy) = log x + log y, log(x/y) = log x − log y, log(xⁿ) = n log x. They turn multiplication into addition — which is why they powered slide rules and why they linearise exponential data in science.", ["growth-decay", "indices-intro"]],
  ["calculus-diff", 5, "Differentiation", "Rates of change and gradients of curves.", "Differentiation finds the gradient at a point: for y = xⁿ, dy/dx = n·xⁿ⁻¹. So y = x² has gradient 2x — steeper as x grows. Stationary points (dy/dx = 0) are maxima, minima or inflections; the second derivative distinguishes them. It is the mathematics of 'how fast right now': velocity from position, growth rate from population.", ["functions", "indices-intro"]],
  ["calculus-int", 5, "Integration", "Accumulation and areas under curves.", "Integration reverses differentiation and measures accumulated change: ∫xⁿ dx = xⁿ⁺¹/(n+1) + c. The area under a velocity–time graph is distance; under a rate–time graph, total amount. Definite integrals subtract boundary values; the +c matters because derivatives lose constants. The Fundamental Theorem links the two halves of calculus into one idea.", ["calculus-diff"]],
  ["kinematics", 4, "Kinematics", "Describing motion: displacement, velocity, acceleration.", "The SUVAT equations link s (displacement), u (initial velocity), v (final velocity), a (acceleration) and t (time) for constant acceleration: v = u + at, s = ut + ½at², v² = u² + 2as. Velocity–time graphs: gradient is acceleration, area is displacement. These are calculus ideas in discrete formula form.", ["straight-lines", "area-perimeter"]],
  ["proof", 4, "Proof & reasoning", "Argument that leaves no doubt.", "Proof is certainty by logic: disproof by counterexample needs one exception; proof by exhaustion checks every case; algebraic proof shows a property holds for all values (prove the sum of two consecutive squares is odd). Identical notation (≡), deduction chains, and 'shown for all n' statements are the standard. This is mathematics as a rigorous language, not just calculation.", ["algebra-expressions", "inequalities"]],
  ["matrices-intro", 5, "Matrices", "Grids of numbers, transformations and systems.", "A matrix is an array; multiplication composes transformations and solves systems compactly. 2×2 matrices act as geometric maps: rotation, reflection, enlargement and shear all have matrix forms. Determinants measure area scaling; a zero determinant collapses the plane — no inverse exists. Matrix methods scale to thousands of equations, the workhorse of computing.", ["simultaneous", "vectors"]],
  ["sets-venn", 2, "Sets & Venn diagrams", "Collections, membership, and overlap logic.", "A set is a collection; Venn diagrams picture overlap. Union (∪) is 'in either', intersection (∩) is 'in both', complement is 'outside'. Two sets: P(A ∪ B) = P(A) + P(B) − P(A ∩ B) — the subtraction stops the overlap being counted twice. Venn diagrams make counting problems, survey data and probability additions visual.", ["probability-basics"], ["sum-one"]],
  ["financial-maths", 3, "Financial mathematics", "Interest, loans, saving — the maths of money.", "Simple interest adds the same amount each period; compound interest adds interest on interest: A = P(1 + r/100)ⁿ. Over 30 years at 7%, money roughly ×8. Depreciation runs the same formula downward. Amortisation splits loan payments between interest and principal. Understanding this topic is worth real money across your whole life.", ["percentages", "growth-decay"], ["simple-cp"]],
  ["bounds", 3, "Error bounds & limits of accuracy", "The range a rounded value could really be.", "A measurement of 3.6 to 1 d.p. really lies in [3.55, 3.65). Calculations on rounded values inherit error: the maximum of a product uses both upper bounds, the minimum both lower. Extreme questions ask for the bounds of a difference or quotient — mixing upper and lower bounds. Engineers live by this: tolerances compound.", ["rounding"], ["round-half"]],
  ["loci-constructions", 2, "Loci & constructions", "Drawing exact figures with compasses; regions defined by rules.", "A locus is the set of points obeying a rule: fixed distance from a point is a circle; equidistant from two points is the perpendicular bisector; equidistant from two lines is an angle bisector. Compasses-only constructions produce these exactly. Combined loci answer real questions: where can you build 5 m from a hedge and 10 m from a well?", ["area-perimeter", "angles-lines"]],
  ["bearings", 2, "Bearings & navigation", "Clockwise angles from north for journeys.", "Bearings measure clockwise from north as three digits: 045°, 180°, 310°. Journeys there-and-back flip bearings by 180° (045° out, 225° back) — a classic exam trap. Combined with the sine and cosine rules, bearings solve navigation: distance and heading of a ship from two observation points.", ["trig-rule"]],
  ["proportional-graphs", 2, "Proportional graphs", "Recognising y = kx and y = k/x from pictures.", "Direct proportion graphs through the origin, straight with constant gradient; inverse proportion graphs are hyperbolas approaching both axes, never touching. Fitting the right model to data — does it double when x doubles, or halve? — is the modelling skill. Real relationships: speed–time at fixed distance (inverse), cost–quantity (direct).", ["proportion", "straight-lines"], ["inv-prop"]],
  ["quadratic-graphs", 3, "Quadratic graphs", "Parabolas: shape, roots, turning point, symmetry.", "y = x² opens upward; the coefficient of x² controls width and direction. Roots are the x-axis crossings; completing the square y = (x − h)² + k puts the turning point at (h, k). Symmetry means the axis of symmetry sits exactly between the roots. Sketching from structure — no table of values — is the skill that scales.", ["quadratics", "completing-square"], ["b-half"]],
  ["algebraic-fractions", 3, "Algebraic fractions", "Simplifying and operating with fraction expressions.", "Factorise first, then cancel: (x² − 9)/(x + 3) = (x+3)(x−3)/(x+3) = x − 3. Adding needs a common denominator built from factors. Equations with algebraic fractions multiply through by the denominator — then check answers, because multiplying can create false solutions. Never cancel term-by-term across a plus sign.", ["fraction-ops", "algebra-expand"], ["cancel-term"]],
  ["iteration", 4, "Numerical iteration", "Finding roots by repeated refinement.", "Some equations refuse algebra — x³ + x = 20 has no neat solution. Iteration rewrites x = g(x) and refines: start with a guess, feed it back in, repeat until the digits settle. Fixed-point iteration and the Newton–Raphson method converge rapidly. Numerical methods power every calculator's solve button.", ["quadratics", "functions"]],
  ["circle-geometry-adv", 4, "Advanced circle geometry", "Intersecting chords, tangents and their theorems.", "Two tangents from an external point are equal in length. The alternate segment theorem: the angle between tangent and chord equals the angle in the alternate segment. Intersecting chords: PA × PB = PC × PD. These theorems, chained together, solve the hardest geometry problems at the top of the paper.", ["circle-theorems"], ["alt-seg", "same-seg"]],
  ["number-bases", 2, "Number bases & binary", "Other bases: binary, hexadecimal, and place value generalized.", "Base 10 is one choice among many. Binary (base 2) uses only 0 and 1: 1011₂ = 8 + 2 + 1 = 11. Computers speak binary; hex (base 16) compresses it — one hex digit is four bits. Converting between bases is place value with a different multiplier: divide by the base repeatedly and read remainders backwards.", ["place-value"]],
  ["logic-maths", 3, "Logic & truth tables", "AND, OR, NOT — the mathematics of reasoning.", "A proposition is true or false. Connectives combine them: AND needs both true, OR needs at least one, NOT flips. Truth tables enumerate every case — two inputs give four rows. The same algebra (Boolean logic) runs digital circuits and database queries; conditional statements and their converse sharpen everyday argument.", ["sets-venn"]],
];

// ─────────────────────────────────────────────────────────────────────────────
// PHYSICS — 18 concepts
// ─────────────────────────────────────────────────────────────────────────────
const PHYSICS: Row[] = [
  ["forces-basics", 1, "Forces", "Pushes and pulls: contact and non-contact interactions.", "A force is a push or pull measured in newtons. Contact forces: friction, air resistance, tension, normal reaction. Non-contact: gravity, magnetism, electrostatic. Force arrows carry magnitude and direction — free-body diagrams strip a situation to its essentials. Balanced forces mean constant velocity, not necessarily stillness.", [], ["bal-motion"]],
  ["motion-graphs", 1, "Motion", "Speed, velocity, acceleration and their graphs.", "Speed is distance over time; velocity adds direction; acceleration is change of velocity per second. Distance–time graph gradient gives speed; velocity–time gradient gives acceleration and area gives distance. A ball thrown up decelerates at 9.8 m/s², stops for an instant, accelerates down — the graph tells the story.", ["forces-basics", "straight-lines"], ["dt-vt"]],
  ["newton-laws", 2, "Newton's laws", "Inertia, F = ma, and action–reaction pairs.", "First law: no resultant force means no change of velocity. Second law: F = ma — force causes acceleration, mass resists it. Third law: forces come in equal, opposite pairs acting on different bodies (you push the wall, the wall pushes you). Weight is a force: W = mg — mass stays, weight varies with g.", ["forces-basics", "motion-graphs"], ["fma-v"]],
  ["momentum", 3, "Momentum & collisions", "Mass in motion, conserved in every collision.", "Momentum p = mv. In any collision or explosion, total momentum is conserved: Σp before = Σp after. A 2 kg trolley at 3 m/s hitting a stationary 1 kg trolley and joining it: 6 = 3v, so v = 2 m/s. Impulse (F·Δt) changes momentum — the reason airbags work: same momentum change, longer time, smaller force.", ["newton-laws"], ["con-pair"]],
  ["energy-conservation", 1, "Energy", "Stored ability to do work — never created or destroyed.", "Energy shifts between stores: kinetic (½mv²), gravitational potential (mgh), elastic (½ke²), thermal, chemical. It is never created or destroyed, only transferred — often via work, heating or waves. Sankey diagrams show where input energy ends up. The conservation law is the accountant's rule of every physical process.", [], ["ke-mass"]],
  ["work-power", 2, "Work, power & efficiency", "Energy transferred by force; rate of transfer; useful fraction.", "Work = force × distance moved in the force's direction (J). Power = work ÷ time (W) — a 60 W bulb transfers 60 J each second. Efficiency = useful output ÷ total input; real machines lose energy to heat and sound. Lifting a 2 kg mass 1.5 m: W = mgh = 29.4 J; doing it in 0.5 s means P ≈ 59 W.", ["energy-conservation"], ["eff-frac"]],
  ["waves-basics", 1, "Waves", "Energy transfer without net matter transport.", "Waves carry energy through oscillation. Transverse waves oscillate perpendicular to travel (light, water); longitudinal parallel (sound). Wave speed v = fλ — frequency times wavelength. Amplitude carries loudness/brightness; frequency carries pitch/colour. Two same-frequency waves interfere: in step reinforces, anti-step cancels.", [], ["freq-pitch"]],
  ["light-optics", 2, "Light & optics", "Reflection, refraction, lenses and the eye.", "Reflection: angle in = angle out. Refraction bends light entering a different density because speed changes — the straw that looks broken in water. Lenses converge or diverge rays; the eye's lens focuses onto the retina. Total internal reflection pipes light down optical fibres — the physics inside the internet.", ["waves-basics", "trig-ratios"], ["norm-miss"]],
  ["sound-acoustics", 2, "Sound", "Longitudinal waves in a medium.", "Sound needs a medium — it cannot travel through vacuum. Frequency sets pitch (20 Hz–20 kHz for humans), amplitude sets loudness (decibels). Echoes measure distance: speed of sound ≈ 340 m/s in air. Standing waves in tubes and strings set musical instruments' notes.", ["waves-basics"], ["sound-vac"]],
  ["electricity-circuits", 2, "Circuits", "Current, voltage, resistance and circuit rules.", "Current is charge flow per second (I = Q/t, amps). Voltage drives it; resistance opposes it: V = IR. Series: one path, same current, voltages add. Parallel: branches share, same voltage, currents add. Circuit analysis is bookkeeping with two rules — Kirchhoff's — that simply say charge and energy are conserved.", ["energy-conservation"], ["series-par"]],
  ["magnetism", 2, "Magnetism", "Fields, poles, induction and electromagnets.", "Magnets have north and south poles; like repel, unlike attract. Field lines exit north, enter south; a compass aligns with them. Electricity and magnetism interconvert: current makes a magnetic field (electromagnets), moving magnets make current (induction) — the pair of ideas behind motors and generators, which are the same machine run backwards.", [], ["motor-gen"]],
  ["em-induction", 3, "Electromagnetic induction", "Generating electricity from changing fields.", "Change the magnetic flux through a coil and a voltage appears across it: more turns, faster change, stronger magnet — more voltage. AC generators spin coils in fields; transformers step voltage up and down via alternating flux (DC won't work). This is how power stations at 25 kV become the 230 V at your socket.", ["magnetism", "electricity-circuits"], ["motor-gen"]],
  ["thermal-physics", 2, "Thermal physics", "Temperature, heat transfer and states of matter.", "Temperature measures average particle kinetic energy; heat is energy in transit. Conduction (particle collision, metals excel), convection (bulk fluid movement), radiation (infrared, needs no medium). Specific heat capacity: 4,200 J raises 1 kg of water 1 °C — water's high value moderates climate and cooks evenly. State changes swap latent heat without temperature change.", ["energy-conservation"], ["heat-temp"]],
  ["pressure-fluids", 2, "Pressure & density", "Force per area; mass per volume.", "Pressure = force ÷ area (Pa). A stiletto dents wood where a flat shoe doesn't — same force, tiny area. In fluids, pressure grows with depth: P = ρgh, acting equally in all directions — the basis of hydraulic brakes and lifts. Density = mass/volume; less dense floats. Atmospheric pressure presses ~100,000 N/m² on everything.", ["forces-basics"], []],
  ["radioactivity", 3, "Radioactivity", "Unstable nuclei emitting alpha, beta, gamma.", "Unstable nuclei decay: alpha (2p+2n, stopped by paper), beta (fast electron, stopped by aluminium), gamma (photon, needs lead). Half-life is the time for half to decay — 10 g of a 1-day half-life source leaves 5 g, then 2.5 g… Decay is random per-atom but statistical in bulk. Uses: carbon dating, medical tracers, sterilisation.", ["atoms-nucleus", "growth-decay"], ["half-life"]],
  ["astrophysics", 3, "Space & astrophysics", "Gravity, orbits, stars and the expanding universe.", "Gravity keeps planets in orbit — circular orbits need centripetal force, supplied by gravity, so satellites 'fall around' Earth. Stars form from collapsing gas, fuse hydrogen, then die as dwarfs, neutron stars or black holes depending on mass. Redshift of distant galaxies reveals expansion — the Big Bang's fingerprint and Hubble's law.", ["gravity-fields", "waves-basics"]],
  ["atoms-nucleus", 2, "Atomic structure", "Nucleus, electrons, and the model's history.", "Atoms: tiny dense nucleus (protons +, neutrons 0) with electrons in orbit. Atomic number = protons (the element's identity); mass number = protons + neutrons; isotopes differ in neutrons. The model evolved: Dalton's spheres → Thomson's plum pudding → Rutherford's nuclear atom from gold-foil scattering → quantum shells.", ["electricity-circuits"], []],
  ["gravity-fields", 2, "Gravity & orbits", "The inverse-square law that runs the universe.", "Every mass attracts every other: F = Gm₁m₂/r². Doubling separation quarters the force — inverse square. Near Earth, g ≈ 9.8 N/kg; in orbit, gravity is the centripetal force. Geostationary satellites match Earth's rotation (24 h period); low orbits race round in ~90 minutes.", ["newton-laws", "proportion"], ["bal-motion"]],
];

// ─────────────────────────────────────────────────────────────────────────────
// CHEMISTRY — 16 concepts
// ─────────────────────────────────────────────────────────────────────────────
const CHEMISTRY: Row[] = [
  ["atoms-elements", 0, "Atoms & elements", "The building blocks of matter.", "An element is one type of atom, listed in the periodic table — 118 known. Atoms: protons (+, in nucleus), neutrons (0), electrons (−, in shells). Atomic number = protons = the element's identity. Chemical reactions rearrange atoms but never change them — matter is conserved.", [], []],
  ["compounds-mixtures", 1, "Compounds & mixtures", "Chemically bonded vs physically mixed.", "Compounds bond elements chemically in fixed ratios — water is always H₂O. Mixtures just sit together — air, sea water, alloys — separable by physical means: filtration, distillation, chromatography. The difference drives everything from ore processing to drug purification.", ["atoms-elements"], []],
  ["periodic-table", 1, "The periodic table", "Elements ordered by atomic number into repeating patterns.", "Rows (periods) fill electron shells; columns (groups) share outer electrons and thus chemistry. Group 1 metals react fiercely with water; group 7 halogens grab electrons; group 8 noble gases react with almost nothing. Trends run both ways: down a group atoms grow and react differently; across a period metallic character fades.", ["atoms-elements", "electron-shells"], ["group-trend"]],
  ["electron-shells", 1, "Electron configuration", "How electrons fill shells — 2, 8, 8.", "Electrons occupy shells: 2 in the first, 8 in the second, 8 in the third (for GCSE). Sodium (11 electrons): 2, 8, 1 — that lonely outer electron explains its reactivity. Full outer shells are stable; everyone else borrows, lends or shares to get there. Configuration is the grammar of bonding.", ["atoms-elements"], []],
  ["ionic-bonding", 2, "Ionic bonding", "Electron transfer between metal and non-metal.", "Metals lose electrons to become positive ions; non-metals gain to become negative. Na gives Cl one electron: Na⁺ + Cl⁻ attract into a giant lattice — high melting points, conductive when molten or dissolved. The formula comes from charge balance: Al³⁺ + O²⁻ needs Al₂O₃. Giant structure means strong electrostatics throughout.", ["electron-shells"], []],
  ["covalent-bonding", 2, "Covalent bonding", "Shared electron pairs between non-metals.", "Non-metals share pairs to complete shells: H₂O, CH₄, O₂ (double bond). Simple molecules: strong bonds inside, weak forces between — hence low boiling points, no conductivity. Giant covalent exceptions: diamond (hard, 3-D network), graphite (layers that slide, conducts — the pencil and the electrode).", ["electron-shells"], []],
  ["metallic-bonding", 2, "Metals & alloys", "Positive ions in a sea of delocalised electrons.", "Metal atoms pack as cations in a mobile 'sea' of shared electrons. That sea conducts electricity and heat, and lets layers slide — malleable, ductile. Alloys mix atom sizes to jam the slide: stronger than pure metals. Stainless steel, bronze, solder — engineered crystals.", ["ionic-bonding"], []],
  ["moles-calcs", 2, "The mole & calculations", "Counting particles by mass: Avogadro's number.", "One mole = 6.02 × 10²³ particles = the relative formula mass in grams. Moles = mass ÷ Mr. Concentration = moles ÷ volume. Balanced equations give ratios: 2H₂ + O₂ → 2H₂O means hydrogen : oxygen : water = 2 : 1 : 2. Limiting reagent: the reactant that runs out first caps the product.", ["compounds-mixtures", "proportion"], ["mr-mass"]],
  ["equations-stoich", 2, "Chemical equations", "Symbol equations, balanced, with state symbols.", "Equations must balance — atoms are conserved: CH₄ + 2O₂ → CO₂ + 2H₂O (4 H, 1 C, 4 O each side). State symbols (s), (l), (g), (aq) add physical meaning. Ionic equations strip spectators to the chemistry that actually happens. Balancing is algebra with atoms.", ["atoms-elements", "linear-equations"], ["mass-balance"]],
  ["rates-reaction", 2, "Rates of reaction", "How fast reactants become products, and how to change it.", "Rate = change ÷ time. Four levers: temperature (particles faster, more energetic collisions), concentration/pressure (more particles per volume), surface area (more exposed surface), catalysts (lower the energy barrier, unchanged at the end). Collision theory explains all four: rate = collision frequency × success fraction.", ["energy-conservation"], []],
  ["energy-changes", 3, "Energy changes & bonding", "Exothermic vs endothermic; bond energy accounting.", "Breaking bonds absorbs energy; making bonds releases it. Exothermic: more released than absorbed — heat given out (combustion, neutralisation). Endothermic: the reverse (photosynthesis, sherbet). Reaction profiles show the energy hill and the activation energy — the barrier catalysts lower.", ["rates-reaction", "energy-conservation"], []],
  ["acids-bases", 2, "Acids, bases & salts", "H⁺ donors, OH⁻ acceptors, and neutralisation.", "Acids release H⁺ (pH < 7); alkalis release OH⁻ (pH > 7); neutralisation: acid + base → salt + water. HCl → chloride salts, H₂SO₄ → sulfates, HNO₃ → nitrates. Titrations measure exact concentrations. Strong vs concentrated: full ionisation vs amount per litre — different axes entirely.", ["compounds-mixtures", "ionic-bonding"], ["strong-conc"]],
  ["electrolysis", 3, "Electrolysis", "Electricity splitting ionic compounds.", "Molten or dissolved ions move to electrodes: positive cations to the cathode (−, gain electrons), negative anions to the anode (+, lose electrons). Electrolysis of brine makes chlorine, hydrogen and sodium hydroxide; of aluminium oxide, the metal itself. Half-equations bookkeep the electrons.", ["ionic-bonding", "electricity-circuits"], []],
  ["organic-intro", 3, "Organic chemistry", "Carbon compounds: crude oil to polymers.", "Carbon chains make millions of compounds. Alkanes are saturated (CₙH₂ₙ₊₂); alkenes have a reactive C=C double bond. Crude oil separates by distillation into fractions; cracking splits big alkanes into small alkenes (feedstock for plastics). Combustion releases energy; incomplete combustion makes deadly CO.", ["covalent-bonding"], []],
  ["equilibria", 4, "Reversible reactions & equilibrium", "Reactions that run both ways, and where they settle.", "Many reactions run both ways: N₂ + 3H₂ ⇌ 2NH₃. Le Chatelier: push the conditions, the equilibrium shifts to oppose the change — more pressure shifts toward fewer gas molecules, more heat toward the endothermic direction. The Haber process balances yield against rate and cost: 450 °C, 200 atm, iron catalyst.", ["rates-reaction", "energy-changes"], []],
  ["analysis-tests", 3, "Chemical analysis", "Tests that identify ions and gases.", "Flame tests and sodium hydroxide precipitates identify metal ions (Cu²⁺ blue, Fe³⁺ brown). Gases: hydrogen squeaky pop with a lit splint, oxygen relights a glowing splint, CO₂ turns limewater cloudy, chlorine bleaches damp litmus. Instrumental methods (mass spec, chromatography) go further: sensitivity, speed, accuracy.", ["atoms-elements", "compounds-mixtures"], []],
];

// ─────────────────────────────────────────────────────────────────────────────
// BIOLOGY — 16 concepts
// ─────────────────────────────────────────────────────────────────────────────
const BIOLOGY: Row[] = [
  ["cells", 0, "Cells", "The unit of life: animal, plant, and specialised.", "All life is cells. Animal cells: nucleus (DNA), cytoplasm, membrane, mitochondria. Plant cells add chloroplasts, a cellulose wall and a vacuole. Specialisation: red cells lose their nucleus to carry more oxygen; sperm pack mitochondria; root hair cells grow huge surface area. Structure always serves function.", [], []],
  ["microscopy", 1, "Microscopy", "Seeing the very small: optical to electron.", "Optical microscopes magnify ~1500× — enough for cells and nuclei. Electron microscopes reach individual organelles and viruses (millions of ×). Magnification = image ÷ real size; standard form handles the scales: a 30 μm cell is 3 × 10⁻⁵ m. Resolution, not just magnification, separates close points.", ["cells", "standard-form"], []],
  ["enzymes", 1, "Enzymes", "Biological catalysts: specific, temperature- and pH-sensitive.", "Enzymes are protein catalysts with active sites shaped for one substrate — lock and key. Denaturation: too hot or wrong pH warps the site and activity dies. Rate climbs with temperature until proteins begin to fail (~37 °C for humans). Substrate concentration saturates: every enzyme busy is maximum rate.", ["cells", "proportion"], []],
  ["digestion", 1, "Digestion", "Breaking food into absorbable molecules.", "Mechanical breakdown (teeth) plus enzymes: amylase → starch to sugar, protease → protein to amino acids, lipase → fat to fatty acids + glycerol. Bile emulsifies fat and neutralises stomach acid. Villi multiply the small intestine's surface — absorption is a surface-area game.", ["enzymes"], []],
  ["circulation", 2, "Circulatory system", "Double circulation: heart, lungs, body.", "Right heart pumps to lungs (oxygen in, CO₂ out); left heart pumps to body — twice through the heart per circuit. Arteries take blood away (thick, high pressure), veins return (valves), capillaries exchange (one cell thick). The pacemaker sets ~70 bpm; exercise multiplies output. Blockage is the world's leading cause of death.", ["cells", "pressure-fluids"], []],
  ["breathing-gas", 1, "Gas exchange", "Lungs, alveoli, and diffusion of O₂ and CO₂.", "Breathing ventilates alveoli — 300 million air sacs, folded like a tennis court's surface, one cell thick, moist. O₂ diffuses into blood, CO₂ out, down concentration gradients. Intercostal muscles and the diaphragm change chest volume: breathe in, volume up, pressure down, air flows in.", ["cells", "diffusion"], []],
  ["diffusion", 1, "Diffusion, osmosis & transport", "Particles moving down gradients.", "Diffusion: particles spread from high to low concentration — smell crossing a room, oxygen into blood. Osmosis is water's version through a partially permeable membrane. Active transport pumps against the gradient using energy — root cells mining minerals. Surface area : volume ratio rules it all: small is fast, big needs transport systems.", ["cells"], []],
  ["photosynthesis", 1, "Photosynthesis", "Light, CO₂ and water into glucose.", "6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂ in chloroplasts. Limiting factors: light intensity, CO₂ concentration, temperature — the graph plateaus as each saturates. Glucose fuels growth, respiration, and storage as starch. Every food chain starts here: plants bank sunlight as chemical energy.", ["enzymes"], []],
  ["respiration", 1, "Respiration", "Releasing energy from glucose.", "Aerobic: glucose + O₂ → CO₂ + H₂O + lots of energy (mitochondria). Anaerobic (no oxygen): glucose → lactic acid (muscle ache, oxygen debt) or → ethanol + CO₂ (yeast, fermentation). Exercise raises rate; recovery repays the debt. Respiration is not breathing — it is the chemistry inside every cell.", ["enzymes", "energy-conservation"], []],
  ["nervous-system", 2, "Nervous system", "Fast electrical signalling: reflexes and reactions.", "Receptors detect, neurons carry, effectors respond. Reflex arc: sensory neuron → relay neuron → motor neuron — automatic, fast, no brain needed (hot pan, hand moves). Synapses pass signals chemically; myelin insulates for speed. Reaction time measures the circuit's health.", ["cells"], []],
  ["hormones", 2, "Hormones & homeostasis", "Chemical messengers keeping the inside constant.", "Endocrine glands release hormones into blood — slower than nerves, longer-lasting. Homeostasis holds constants: blood glucose (insulin lowers, glucagon raises), body temperature 37 °C (sweat, shiver, vasodilation), water balance (ADH, kidneys). Negative feedback: the deviation itself triggers the correction.", ["nervous-system", "diffusion"], []],
  ["genetics", 2, "Genetics & inheritance", "DNA, genes, and how traits pass on.", "DNA is the double helix; genes are instructions for proteins. Alleles are gene versions: dominant (capital) shows if present, recessive needs both copies. Punnett squares predict offspring ratios: two carriers Aa × Aa → 3 : 1. Sex determination: XX female, XY male. Meiosis halves chromosomes so children get one set from each parent.", ["cells", "probability-basics"], []],
  ["evolution", 3, "Evolution & selection", "Variation, selection, and change over generations.", "Mutations create variation; selection keeps the fittest — those who reproduce more pass on their alleles. Darwin's finches: beaks match food sources. Antibiotic resistance is evolution in a petri dish: survive the drug, multiply, repeat. Speciation follows isolation — separated populations drift apart until they can no longer interbreed.", ["genetics"], []],
  ["ecosystems", 2, "Ecosystems & cycles", "Food webs, energy loss, and material cycles.", "Producers capture sunlight; consumers eat; decomposers recycle. Energy transfers lose ~90% per level — hence short food chains and few top predators. Carbon cycle: photosynthesis in, respiration and combustion out. Water cycle: evaporation, condensation, precipitation. Nitrogen cycle: bacteria make the air fertile.", ["photosynthesis", "respiration"], []],
  ["biodiversity", 3, "Biodiversity & human impact", "Variety of life, and what we are doing to it.", "Biodiversity — species, genetic and ecosystem variety — makes systems resilient. Human pressures: habitat loss, pollution, overfishing, invasive species, climate change. Conservation: reserves, seed banks, captive breeding, sustainable quotas. The tension: development now vs stability later — and the maths of tipping points.", ["ecosystems"], []],
  ["immune-health", 3, "Health, disease & immunity", "Pathogens, defence, and vaccines.", "Pathogens: viruses (hijack cells), bacteria (toxins), fungi, protists. Barriers first (skin, mucus, acid), then white cells: phagocytosis, then antibodies shaped to one antigen. Vaccines train the system safely — memory cells stand ready. Antivirals are hard; antibiotics only work on bacteria — misuse breeds resistance.", ["cells", "evolution"], []],
];

// ─────────────────────────────────────────────────────────────────────────────
// COMPUTING — 18 concepts
// ─────────────────────────────────────────────────────────────────────────────
const COMPUTING: Row[] = [
  ["what-is-code", 0, "What is code?", "Instructions a computer executes, written precisely.", "Code is a set of unambiguous instructions: computers do exactly what you say, not what you mean. Programs are written in languages (Python, JavaScript) that translate to machine operations. The core skill is decomposition: breaking 'make a game' into 'draw a paddle, move it, bounce a ball'. Precision is the discipline; creativity is the reward.", [], []],
  ["variables", 0, "Variables & types", "Named boxes holding values: numbers, strings, booleans.", "A variable names a value: score = 0. Types matter: integers (3), floats (3.14), strings ('hello'), booleans (true/false). Assignment stores; expressions compute: score = score + 10. Casting converts: int('42') gives the number. Naming well is half of readable code.", ["what-is-code"], []],
  ["conditionals", 0, "Conditionals", "Decisions: if, else if, else.", "Branching makes programs respond: if temperature > 30 → 'hot', elif > 20 → 'warm', else → 'cool'. Conditions are boolean expressions: ==, !=, <, >, and/or/not. Nesting handles compound logic, but flat conditions with early returns usually read better. Every app you use is mostly conditionals.", ["variables"], []],
  ["loops", 0, "Loops", "Repetition: for (known count), while (known condition).", "for loops repeat a known number of times (each item in a list); while loops repeat until a condition changes — beware infinite loops. Loop + list is the workhorse of data processing: total = 0; for x in prices: total += x. Off-by-one errors are the classic bug: does the range include the end?", ["variables"], []],
  ["lists-arrays", 1, "Lists & arrays", "Ordered collections with index access.", "A list holds many values in order: fruits[0] is the first. Append adds, remove deletes, len measures. Iteration visits each: for fruit in fruits. Lists nest: a grid is a list of lists — the foundation of images, boards, spreadsheets. Choosing the right structure (list, set, dictionary) is half the design.", ["variables", "loops"], []],
  ["functions-code", 1, "Functions & decomposition", "Reusable named blocks with inputs and outputs.", "def greet(name): return 'Hello, ' + name — define once, call many. Parameters take input; return gives output. Decomposition: big problems split into small named functions you can test separately. DRY — don't repeat yourself — copies are bugs waiting to diverge.", ["variables", "conditionals"], []],
  ["dictionaries", 1, "Dictionaries & hashing", "Key–value lookup in constant time.", "A dictionary maps keys to values: ages['Amina'] = 14 — instant lookup regardless of size, via hashing. Perfect for counting (tally of letters), indexing (name → record), caching (computed → saved). Sets hold unique items with fast membership. Choosing between list, dict and set changes performance by orders of magnitude.", ["lists-arrays"], []],
  ["algorithms-search", 2, "Searching algorithms", "Linear vs binary: scan or halve.", "Linear search checks each item — works on anything, slow on big data. Binary search halves the candidates each step — 1,000,000 items found in ~20 steps — but needs sorted data. The lesson: algorithm choice can beat any amount of hardware speed. Sorting first is often worth it.", ["lists-arrays", "conditionals"], []],
  ["algorithms-sort", 2, "Sorting algorithms", "Bubble, merge, and the cost of ordering.", "Bubble sort swaps neighbours — simple, O(n²), fine for tiny inputs. Merge sort splits, sorts halves, merges — O(n log n), scales to millions. Watching 30 bubbles vs 30 merges makes the difference visceral. Big-O notation measures growth: the shape of the cost curve, not the milliseconds.", ["algorithms-search"], []],
  ["recursion", 3, "Recursion", "Functions that call themselves, with a base case.", "A recursive function solves a problem by solving smaller versions of itself: factorial(n) = n × factorial(n−1), stopping at factorial(0) = 1. The base case stops infinite descent; the call stack remembers where to return. Trees, mazes and divide-and-conquer algorithms are natural recursions.", ["functions-code"], []],
  ["complexity", 3, "Computational thinking & Big-O", "Abstraction, decomposition, and growth rates.", "Computational thinking: decompose the problem, abstract away detail, recognise patterns, design an algorithm. Big-O classes: O(1) instant, O(log n) halving, O(n) a pass, O(n log n) good sorting, O(n²) pairwise, O(2ⁿ) intractable. The difference between 2ⁿ and n log n at n = 100 is the difference between impossible and instant.", ["algorithms-sort", "functions-code"], []],
  ["binary-data", 1, "Binary & data representation", "Everything is bits: numbers, text, images, sound.", "Computers store everything in binary. 8 bits = 1 byte = 256 values. Text maps numbers to letters (ASCII, Unicode — emoji included). Images are pixel grids: RGB triples; more bits, more colours. Sound samples amplitude thousands of times per second. Compression removes redundancy: lossless (ZIP) vs lossy (JPEG, MP3).", ["number-bases"], []],
  ["networks", 2, "Networks & the internet", "Packets, protocols, and the web's stack.", "The internet moves packets: data chopped, addressed (IP), routed hop by hop, reassembled (TCP guarantees order). DNS turns names into addresses. HTTP/HTTPS request web pages; latency and bandwidth set the experience. Client and server split the work — your browser asks, servers answer.", ["binary-data"], []],
  ["cybersecurity", 2, "Cybersecurity", "Threats and defences: hashing, encryption, common sense.", "Threats: phishing (trick the human), malware (poison the machine), brute force (guess passwords). Defences: strong unique passwords, 2FA, encryption (scramble without the key), hashing (one-way fingerprint for stored passwords), updates (patch the holes). Security is a systems property — the weakest link is usually a person, not a cipher.", ["networks", "logic-maths"], []],
  ["databases-sql", 3, "Databases", "Structured storage and queries.", "Relational databases store tables; SQL selects: SELECT name FROM students WHERE grade > 80. Primary keys identify rows; foreign keys link tables. Normalisation removes duplication. Indexes trade write speed for read speed. Nearly every app you use is a database with a user interface on top.", ["dictionaries"], []],
  ["web-stack", 2, "How the web works", "HTML structure, CSS style, JavaScript behaviour.", "HTML gives structure (headings, paragraphs, links), CSS gives style (colours, layout, animation), JavaScript gives behaviour (respond to clicks, fetch data). The DOM is the live tree the browser manipulates. Front-end runs in the browser; back-end runs on servers with databases. Learning all three is the fastest path from idea to product.", ["networks"], []],
  ["ai-basics", 3, "AI & machine learning", "Programs that learn patterns from data.", "Classical programming: rules + data → answers. Machine learning: data + answers → rules. A model trains on examples (cats vs dogs) and generalises to new ones. Neural networks stack simple weighted sums through nonlinear activations; training adjusts weights to reduce error. Garbage in, garbage out: data quality caps model quality.", ["complexity", "statistics-data"], []],
  ["statistics-data", 2, "Data analysis & statistics", "Summarise, visualise, and question data with code.", "Load a dataset, compute summaries (mean, median, spread), plot distributions, and hunt for outliers and bias. Correlation ≠ causation; sampling bias poisons conclusions; averages hide distributions. With code, a thousand rows take a second — the thinking is the hard part, and it is the same thinking as good science.", ["averages", "lists-arrays"], ["outlier-mean"]],
];

// ─────────────────────────────────────────────────────────────────────────────
// Assemble & validate the genome
// ─────────────────────────────────────────────────────────────────────────────

export const CONCEPTS: Concept[] = [
  ...build("maths", MATHS),
  ...build("physics", PHYSICS),
  ...build("chemistry", CHEMISTRY),
  ...build("biology", BIOLOGY),
  ...build("computing", COMPUTING),
];

export const CONCEPTS_BY_ID: Record<string, Concept> = Object.fromEntries(
  CONCEPTS.map((c) => [c.id, c]),
);

export function getConcept(id: string): Concept | undefined {
  return CONCEPTS_BY_ID[id];
}

export function bySubject(subject: SubjectId): Concept[] {
  return CONCEPTS.filter((c) => c.subject === subject);
}

/** Depth-first ancestors (transitive prerequisites), nearest first. */
export function ancestorsOf(id: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  const walk = (cid: string) => {
    for (const p of CONCEPTS_BY_ID[cid]?.prereqs ?? []) {
      if (!seen.has(p)) {
        seen.add(p);
        out.push(p);
        walk(p);
      }
    }
  };
  walk(id);
  return out;
}

/** Direct + transitive dependents (concepts that need this one). */
export function descendantsOf(id: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  const walk = (cid: string) => {
    for (const c of CONCEPTS) {
      if (c.prereqs.includes(cid) && !seen.has(c.id)) {
        seen.add(c.id);
        out.push(c.id);
        walk(c.id);
      }
    }
  };
  walk(id);
  return out;
}

/** i18n KEYS, not English text — render with `t(STAGE_NAMES[stage])` so the
 *  stage band reads in the learner's language (keys `stage.0`…`stage.5` are
 *  authored for all 15 languages in lib/i18n.ts). */
export const STAGE_NAMES: Record<StageId, string> = {
  0: "stage.0",
  1: "stage.1",
  2: "stage.2",
  3: "stage.3",
  4: "stage.4",
  5: "stage.5",
};
