// One-shot: add the 17 native tutor keys (soc.*) to the six original content
// languages (es fr pt ar sw hi), so the Socratic tutor speaks their language
// everywhere. Anchored per dictionary declaration.
import fs from "node:fs";

const LANGS = {
  es: {"soc.opener1":"Busquemos la razón juntos —","soc.opener2":"Buena pregunta. Antes que nada: ¿qué te dice tu intuición?","soc.opener3":"Vamos despacio y veamos qué pregunta de verdad —","soc.opener4":"Interesante. En vez de la respuesta, encontremos la idea —","soc.opener5":"Yo pregunto, tú respondes: de lo que ya sabes, ¿qué se conecta con esto?","soc.refuse":"No te doy la respuesta directa — pero te llevo hasta ella.","soc.sure":"¿De qué parte estás seguro ahora mismo?","soc.whyQ":"La pregunta: si pudieras cambiar UN número de tu trabajo, ¿cuál cambio lo explicaría todo?","soc.stuckLead":"Lo partimos en tres pasos.","soc.given":"Prueba esto: escribe exactamente qué te DAN y qué te PIDEN.","soc.givenQ":"¿Qué te dan aquí?","soc.restate":"Ahora — ¿puedes decir el problema con tus propias palabras?","soc.start":"Empecemos por lo que ya sabes.","soc.step1":"Paso 1 — escribe el dato y lo pedido.","soc.step2":"Paso 2 — ¿qué idea de la lección los conecta?","soc.step3":"Paso 3 — el razonamiento","soc.step4":"Comprueba: la opción correcta era"},
  fr: {"soc.opener1":"Cherchons la raison ensemble —","soc.opener2":"Bonne question. D'abord : que dit ton intuition ?","soc.opener3":"Ralentissons et regardons ce que la question demande vraiment —","soc.opener4":"Intéressant. Plutôt que la réponse, trouvons l'idée —","soc.opener5":"Je pose la question, tu réponds : parmi ce que tu sais déjà, qu'est-ce qui s'y rattache ?","soc.refuse":"Je ne donne pas la réponse directement — mais je t'y amène.","soc.sure":"Quelle partie es-tu sûr de maîtriser, là ?","soc.whyQ":"La question : si tu pouvais changer UN seul nombre de ton calcul, lequel rendrait tout cohérent ?","soc.stuckLead":"Découpons en trois étapes.","soc.given":"Essaie ceci : écris exactement ce qu'on te DONNE et ce qu'on te DEMANDE.","soc.givenQ":"Qu'est-ce qu'on te donne ici ?","soc.restate":"Maintenant — peux-tu reformuler le problème avec tes mots ?","soc.start":"Commençons par ce que tu sais déjà.","soc.step1":"Étape 1 — écris la donnée et l'inconnue.","soc.step2":"Étape 2 — quelle idée du cours les relie ?","soc.step3":"Étape 3 — le raisonnement","soc.step4":"Vérifie : la bonne réponse était"},
  pt: {"soc.opener1":"Vamos descobrir o motivo juntos —","soc.opener2":"Boa pergunta. Antes de tudo: o que a sua intuição diz?","soc.opener3":"Vamos devagar e ver o que a questão realmente pede —","soc.opener4":"Interessante. Em vez da resposta, vamos achar a ideia —","soc.opener5":"Eu pergunto, você responde: do que você já sabe, o que se conecta com isso?","soc.refuse":"Não dou a resposta direta — mas te levo até ela.","soc.sure":"De qual parte você tem certeza agora?","soc.whyQ":"A pergunta: se você pudesse mudar UM número do seu cálculo, qual mudança deixaria tudo certo?","soc.stuckLead":"Vamos dividir em três passos.","soc.given":"Tente isto: escreva exatamente o que é DADO e o que é PEDIDO.","soc.givenQ":"O que é dado aqui?","soc.restate":"Agora — consegue dizer o problema com suas próprias palavras?","soc.start":"Vamos começar pelo que você já sabe.","soc.step1":"Passo 1 — escreva o dado e o pedido.","soc.step2":"Passo 2 — qual ideia da lição os conecta?","soc.step3":"Passo 3 — o raciocínio","soc.step4":"Confira: a alternativa correta era"},
  ar: {"soc.opener1":"لنجد السبب معًا —","soc.opener2":"سؤال جيد. قبل كل شيء: ماذا يقول حدسك؟","soc.opener3":"لنمهل قليلًا ونرَ ما يسأله السؤال فعلًا —","soc.opener4":"مثير للاهتمام. بدل الجواب، لنجد الفكرة —","soc.opener5":"أسأل وأنت تجيب: مما تعرفه سلفًا، ما الذي يرتبط بهذا؟","soc.refuse":"لن أعطيك الجواب مباشرة — لكنني سأوصلك إليه.","soc.sure":"في أي جزء أنت متأكد الآن؟","soc.whyQ":"السؤال: لو غيّرت رقمًا واحدًا فقط في حلك، فأي تغيير يجعل كل شيء متماسكًا؟","soc.stuckLead":"نقسمها إلى ثلاث خطوات.","soc.given":"جرّب هذا: اكتب بدقة ما هو معلوم وما هو مطلوب.","soc.givenQ":"ما المعلوم هنا؟","soc.restate":"الآن — هل تستطيع إعادة صياغة المسألة بكلماتك؟","soc.start":"لنبدأ مما تعرفه.","soc.step1":"خطوة ١ — اكتب المعلوم والمطلوب.","soc.step2":"خطوة ٢ — أي فكرة من الدرس تصل بينهما؟","soc.step3":"خطوة ٣ — الاستدلال","soc.step4":"تحقّق: كانت الإجابة الصحيحة"},
  sw: {"soc.opener1":"Tufanye sababu pamoja —","soc.opener2":"Swali zuri. Kabla ya yote: akili yako inasema nini?","soc.opener3":"Tufanye taratibu tuone swali linacha uliza nini —","soc.opener4":"Kuvutia. Badala ya jibu, tufikirie wazo —","soc.opener5":"Mimi nauliza, wewe unajibu: kwa unachojua tayari, nini kinaunganisha na hili?","soc.refuse":"Sitakupa jibu moja kwa moja — lakini nitakufikisha hapo.","soc.sure":"Sehemu gani una uhakika sasa?","soc.whyQ":"Swali: ungebadilisha NAMBA moja tu kwenye kazi yako, mabadiliko gani yangefanya yote yakubaliane?","soc.stuckLead":"Tigawanye katika hatua tatu.","soc.given":"Jaribu hii: andika kwa umakini kilichotolewa na kinachotafutwa.","soc.givenQ":"Kilichotolewa hapa ni nini?","soc.restate":"Sasa — unaweza kusema swali kwa maneno yako mwenyewe?","soc.start":"Tuanze na unachojua.","soc.step1":"Hatua ya 1 — andika kilichotolewa na kinachotafutwa.","soc.step2":"Hatua ya 2 — wazo gani la somo linaunganisha vitu hivi?","soc.step3":"Hatua ya 3 — hoja","soc.step4":"Angalia: jibu sahihi lilikuwa"},
  hi: {"soc.opener1":"आइए कारण साथ मिलकर खोजें —","soc.opener2":"अच्छा सवाल। पहले यह बताइए — आपका अंदाज़ा क्या कहता है?","soc.opener3":"धीरे चलें और देखें सवाल सच में क्या पूछ रहा है —","soc.opener4":"दिलचस्प है। जवाब की जगह पहले विचार खोजें —","soc.opener5":"मैं पूछूँगा, आप बताइए: जो आप पहले से जानते हैं, उसमें से क्या इससे जुड़ता है?","soc.refuse":"सीधा जवाब नहीं दूँगा — पर आपको वहाँ तक पहुँचा दूँगा।","soc.sure":"अभी किस हिस्से में आप निश्चित हैं?","soc.whyQ":"सवाल यह: अपने हल में सिर्फ़ एक संख्या बदल सकते, तो कौन-सा बदलाव सब कुछ समझा देगा?","soc.stuckLead":"तीन चरणों में तोड़ते हैं।","soc.given":"यह कीजिए: ठीक-ठीक लिखिए क्या दिया गया है और क्या पूछा गया है।","soc.givenQ":"यहाँ क्या दिया गया है?","soc.restate":"अब — सवाल को अपने शब्दों में कह सकते हैं?","soc.start":"जो जानते हैं वहीं से शुरू करें।","soc.step1":"चरण १ — दिया गया और पूछा गया लिखिए।","soc.step2":"चरण २ — पाठ का कौन-सा विचार इन दोनों को जोड़ता है?","soc.step3":"चरण ३ — तर्क","soc.step4":"जाँचिए: सही विकल्प था"},
};

const src = fs.readFileSync("lib/i18n.ts", "utf8");
const lines = src.split("\n");
let total = 0;
for (const [code, map] of Object.entries(LANGS)) {
  const anchor = lines.findIndex((l) => new RegExp(`^(?:export )?const ${code}: Dict = \\{$`).test(l));
  if (anchor < 0) { console.error(`${code}: anchor not found`); process.exit(1); }
  const block = Object.entries(map).map(([k, v]) => `  "${k}": ${JSON.stringify(v)},`);
  lines.splice(anchor + 1, 0, block.join("\n"));
  total += block.length;
  console.log(`${code}: +${block.length}`);
}
fs.writeFileSync("lib/i18n.ts", lines.join("\n"));
console.log(`total +${total}`);
